/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CreditScoring } from "./CreditScoring";
export type { Lending } from "./Lending";
export type { Lock } from "./Lock";
